/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractUseCaseValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mx.kukulkan.dsl.usecase.useCase.UseCasePackage.eINSTANCE);
		return result;
	}
}
