/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUseCaseScopeProvider extends DelegatingScopeProvider {
}
