/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UseCaseRuntimeModule extends AbstractUseCaseRuntimeModule {
}
