/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UseCaseStandaloneSetup extends UseCaseStandaloneSetupGenerated {

	def static void doSetup() {
		new UseCaseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
