/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ui;

import com.google.inject.Injector;
import mx.kukulkan.dsl.usecase.ui.internal.UsecaseActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UseCaseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UsecaseActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UsecaseActivator activator = UsecaseActivator.getInstance();
		return activator != null ? activator.getInjector(UsecaseActivator.MX_KUKULKAN_DSL_USECASE_USECASE) : null;
	}

}
