/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UseCaseAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mx/kukulkan/dsl/usecase/parser/antlr/internal/InternalUseCase.tokens");
	}
}
