/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.parser.antlr;

import com.google.inject.Inject;
import mx.kukulkan.dsl.usecase.parser.antlr.internal.InternalUseCaseParser;
import mx.kukulkan.dsl.usecase.services.UseCaseGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UseCaseParser extends AbstractAntlrParser {

	@Inject
	private UseCaseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUseCaseParser createParser(XtextTokenStream stream) {
		return new InternalUseCaseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public UseCaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UseCaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
