/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ui.contentassist;

import mx.kukulkan.dsl.usecase.ui.contentassist.AbstractUseCaseProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class UseCaseProposalProvider extends AbstractUseCaseProposalProvider {
}
