/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mx.kukulkan.dsl.usecase.UseCaseRuntimeModule;
import mx.kukulkan.dsl.usecase.UseCaseStandaloneSetup;
import mx.kukulkan.dsl.usecase.ide.UseCaseIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UseCaseIdeSetup extends UseCaseStandaloneSetup {
  @Override
  public Injector createInjector() {
    UseCaseRuntimeModule _useCaseRuntimeModule = new UseCaseRuntimeModule();
    UseCaseIdeModule _useCaseIdeModule = new UseCaseIdeModule();
    return Guice.createInjector(Modules2.mixin(_useCaseRuntimeModule, _useCaseIdeModule));
  }
}
