/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ide;

import mx.kukulkan.dsl.usecase.ide.AbstractUseCaseIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UseCaseIdeModule extends AbstractUseCaseIdeModule {
}
