/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase;

import mx.kukulkan.dsl.usecase.UseCaseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UseCaseStandaloneSetup extends UseCaseStandaloneSetupGenerated {
  public static void doSetup() {
    new UseCaseStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
