/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase;

import mx.kukulkan.dsl.usecase.AbstractUseCaseRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UseCaseRuntimeModule extends AbstractUseCaseRuntimeModule {
}
