/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ui;

import mx.kukulkan.dsl.usecase.ui.AbstractUseCaseUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UseCaseUiModule extends AbstractUseCaseUiModule {
  public UseCaseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
