/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.scoping;

import mx.kukulkan.dsl.usecase.scoping.AbstractUseCaseScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class UseCaseScopeProvider extends AbstractUseCaseScopeProvider {
}
