/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complete Action Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getUserActionsBlock <em>User Actions Block</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getSystemActionsBlock <em>System Actions Block</em>}</li>
 * </ul>
 *
 * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getCompleteActionBlock()
 * @model
 * @generated
 */
public interface CompleteActionBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>User Actions Block</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>User Actions Block</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>User Actions Block</em>' attribute list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getCompleteActionBlock_UserActionsBlock()
   * @model unique="false"
   * @generated
   */
  EList<String> getUserActionsBlock();

  /**
   * Returns the value of the '<em><b>System Actions Block</b></em>' containment reference list.
   * The list contents are of type {@link mx.kukulkan.dsl.usecase.useCase.SystemActionBlock}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System Actions Block</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System Actions Block</em>' containment reference list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getCompleteActionBlock_SystemActionsBlock()
   * @model containment="true"
   * @generated
   */
  EList<SystemActionBlock> getSystemActionsBlock();

} // CompleteActionBlock
