/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
