/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCaseFlow#getCompleteActionsBlock <em>Complete Actions Block</em>}</li>
 * </ul>
 *
 * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCaseFlow()
 * @model
 * @generated
 */
public interface UseCaseFlow extends EObject
{
  /**
   * Returns the value of the '<em><b>Complete Actions Block</b></em>' containment reference list.
   * The list contents are of type {@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Complete Actions Block</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complete Actions Block</em>' containment reference list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCaseFlow_CompleteActionsBlock()
   * @model containment="true"
   * @generated
   */
  EList<CompleteActionBlock> getCompleteActionsBlock();

} // UseCaseFlow
