/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getName <em>Name</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCaseName <em>Use Case Name</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getActors <em>Actors</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getConcepts <em>Concepts</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCasesFlow <em>Use Cases Flow</em>}</li>
 * </ul>
 *
 * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase()
 * @model
 * @generated
 */
public interface UseCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Use Case Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Case Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Case Name</em>' attribute.
   * @see #setUseCaseName(String)
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase_UseCaseName()
   * @model
   * @generated
   */
  String getUseCaseName();

  /**
   * Sets the value of the '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCaseName <em>Use Case Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use Case Name</em>' attribute.
   * @see #getUseCaseName()
   * @generated
   */
  void setUseCaseName(String value);

  /**
   * Returns the value of the '<em><b>Actors</b></em>' reference list.
   * The list contents are of type {@link mx.kukulkan.dsl.usecase.useCase.Actor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actors</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actors</em>' reference list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase_Actors()
   * @model
   * @generated
   */
  EList<Actor> getActors();

  /**
   * Returns the value of the '<em><b>Concepts</b></em>' reference list.
   * The list contents are of type {@link mx.kukulkan.dsl.usecase.useCase.Concept}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concepts</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concepts</em>' reference list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase_Concepts()
   * @model
   * @generated
   */
  EList<Concept> getConcepts();

  /**
   * Returns the value of the '<em><b>Use Cases Flow</b></em>' containment reference list.
   * The list contents are of type {@link mx.kukulkan.dsl.usecase.useCase.UseCaseFlow}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Cases Flow</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Cases Flow</em>' containment reference list.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage#getUseCase_UseCasesFlow()
   * @model containment="true"
   * @generated
   */
  EList<UseCaseFlow> getUseCasesFlow();

} // UseCase
