/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see mx.kukulkan.dsl.usecase.useCase.UseCasePackage
 * @generated
 */
public interface UseCaseFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UseCaseFactory eINSTANCE = mx.kukulkan.dsl.usecase.useCase.impl.UseCaseFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Requirements Use Case Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Requirements Use Case Model</em>'.
   * @generated
   */
  RequirementsUseCaseModel createRequirementsUseCaseModel();

  /**
   * Returns a new object of class '<em>Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actor</em>'.
   * @generated
   */
  Actor createActor();

  /**
   * Returns a new object of class '<em>Concept</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Concept</em>'.
   * @generated
   */
  Concept createConcept();

  /**
   * Returns a new object of class '<em>Use Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Use Case</em>'.
   * @generated
   */
  UseCase createUseCase();

  /**
   * Returns a new object of class '<em>Flow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow</em>'.
   * @generated
   */
  UseCaseFlow createUseCaseFlow();

  /**
   * Returns a new object of class '<em>Complete Action Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Complete Action Block</em>'.
   * @generated
   */
  CompleteActionBlock createCompleteActionBlock();

  /**
   * Returns a new object of class '<em>System Action Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Action Block</em>'.
   * @generated
   */
  SystemActionBlock createSystemActionBlock();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UseCasePackage getUseCasePackage();

} //UseCaseFactory
