/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mx.kukulkan.dsl.usecase.useCase.UseCaseFactory
 * @model kind="package"
 * @generated
 */
public interface UseCasePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "useCase";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kukulkan.mx/dsl/usecase/UseCase";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "useCase";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UseCasePackage eINSTANCE = mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl.init();

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl <em>Requirements Use Case Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getRequirementsUseCaseModel()
   * @generated
   */
  int REQUIREMENTS_USE_CASE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Actors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENTS_USE_CASE_MODEL__ACTORS = 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENTS_USE_CASE_MODEL__DATA = 1;

  /**
   * The feature id for the '<em><b>Usecases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENTS_USE_CASE_MODEL__USECASES = 2;

  /**
   * The number of structural features of the '<em>Requirements Use Case Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENTS_USE_CASE_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.ActorImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getActor()
   * @generated
   */
  int ACTOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.ConceptImpl <em>Concept</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.ConceptImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getConcept()
   * @generated
   */
  int CONCEPT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Concept Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT__CONCEPT_DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Concept</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.UseCaseImpl <em>Use Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCaseImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getUseCase()
   * @generated
   */
  int USE_CASE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Use Case Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__USE_CASE_NAME = 1;

  /**
   * The feature id for the '<em><b>Actors</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__ACTORS = 2;

  /**
   * The feature id for the '<em><b>Concepts</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__CONCEPTS = 3;

  /**
   * The feature id for the '<em><b>Use Cases Flow</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__USE_CASES_FLOW = 4;

  /**
   * The number of structural features of the '<em>Use Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.UseCaseFlowImpl <em>Flow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCaseFlowImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getUseCaseFlow()
   * @generated
   */
  int USE_CASE_FLOW = 4;

  /**
   * The feature id for the '<em><b>Complete Actions Block</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FLOW__COMPLETE_ACTIONS_BLOCK = 0;

  /**
   * The number of structural features of the '<em>Flow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FLOW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.CompleteActionBlockImpl <em>Complete Action Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.CompleteActionBlockImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getCompleteActionBlock()
   * @generated
   */
  int COMPLETE_ACTION_BLOCK = 5;

  /**
   * The feature id for the '<em><b>User Actions Block</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLETE_ACTION_BLOCK__USER_ACTIONS_BLOCK = 0;

  /**
   * The feature id for the '<em><b>System Actions Block</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLETE_ACTION_BLOCK__SYSTEM_ACTIONS_BLOCK = 1;

  /**
   * The number of structural features of the '<em>Complete Action Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLETE_ACTION_BLOCK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.SystemActionBlockImpl <em>System Action Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.kukulkan.dsl.usecase.useCase.impl.SystemActionBlockImpl
   * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getSystemActionBlock()
   * @generated
   */
  int SYSTEM_ACTION_BLOCK = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ACTION_BLOCK__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ACTION_BLOCK__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>System Action Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ACTION_BLOCK_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel <em>Requirements Use Case Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Requirements Use Case Model</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel
   * @generated
   */
  EClass getRequirementsUseCaseModel();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getActors <em>Actors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actors</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getActors()
   * @see #getRequirementsUseCaseModel()
   * @generated
   */
  EReference getRequirementsUseCaseModel_Actors();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getData()
   * @see #getRequirementsUseCaseModel()
   * @generated
   */
  EReference getRequirementsUseCaseModel_Data();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getUsecases <em>Usecases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Usecases</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel#getUsecases()
   * @see #getRequirementsUseCaseModel()
   * @generated
   */
  EReference getRequirementsUseCaseModel_Usecases();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.Actor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Actor#getName()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.Actor#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Actor#getDescription()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Description();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.Concept <em>Concept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concept</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Concept
   * @generated
   */
  EClass getConcept();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.Concept#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Concept#getName()
   * @see #getConcept()
   * @generated
   */
  EAttribute getConcept_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.Concept#getConceptDescription <em>Concept Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Concept Description</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.Concept#getConceptDescription()
   * @see #getConcept()
   * @generated
   */
  EAttribute getConcept_ConceptDescription();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase
   * @generated
   */
  EClass getUseCase();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase#getName()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCaseName <em>Use Case Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Use Case Name</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCaseName()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_UseCaseName();

  /**
   * Returns the meta object for the reference list '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getActors <em>Actors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Actors</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase#getActors()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Actors();

  /**
   * Returns the meta object for the reference list '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getConcepts <em>Concepts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Concepts</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase#getConcepts()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_Concepts();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCasesFlow <em>Use Cases Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Use Cases Flow</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCase#getUseCasesFlow()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_UseCasesFlow();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.UseCaseFlow <em>Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flow</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCaseFlow
   * @generated
   */
  EClass getUseCaseFlow();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.UseCaseFlow#getCompleteActionsBlock <em>Complete Actions Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Complete Actions Block</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.UseCaseFlow#getCompleteActionsBlock()
   * @see #getUseCaseFlow()
   * @generated
   */
  EReference getUseCaseFlow_CompleteActionsBlock();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock <em>Complete Action Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complete Action Block</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock
   * @generated
   */
  EClass getCompleteActionBlock();

  /**
   * Returns the meta object for the attribute list '{@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getUserActionsBlock <em>User Actions Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>User Actions Block</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getUserActionsBlock()
   * @see #getCompleteActionBlock()
   * @generated
   */
  EAttribute getCompleteActionBlock_UserActionsBlock();

  /**
   * Returns the meta object for the containment reference list '{@link mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getSystemActionsBlock <em>System Actions Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>System Actions Block</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.CompleteActionBlock#getSystemActionsBlock()
   * @see #getCompleteActionBlock()
   * @generated
   */
  EReference getCompleteActionBlock_SystemActionsBlock();

  /**
   * Returns the meta object for class '{@link mx.kukulkan.dsl.usecase.useCase.SystemActionBlock <em>System Action Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Action Block</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.SystemActionBlock
   * @generated
   */
  EClass getSystemActionBlock();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.SystemActionBlock#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.SystemActionBlock#getName()
   * @see #getSystemActionBlock()
   * @generated
   */
  EAttribute getSystemActionBlock_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.kukulkan.dsl.usecase.useCase.SystemActionBlock#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see mx.kukulkan.dsl.usecase.useCase.SystemActionBlock#getDescription()
   * @see #getSystemActionBlock()
   * @generated
   */
  EAttribute getSystemActionBlock_Description();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UseCaseFactory getUseCaseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl <em>Requirements Use Case Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getRequirementsUseCaseModel()
     * @generated
     */
    EClass REQUIREMENTS_USE_CASE_MODEL = eINSTANCE.getRequirementsUseCaseModel();

    /**
     * The meta object literal for the '<em><b>Actors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENTS_USE_CASE_MODEL__ACTORS = eINSTANCE.getRequirementsUseCaseModel_Actors();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENTS_USE_CASE_MODEL__DATA = eINSTANCE.getRequirementsUseCaseModel_Data();

    /**
     * The meta object literal for the '<em><b>Usecases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENTS_USE_CASE_MODEL__USECASES = eINSTANCE.getRequirementsUseCaseModel_Usecases();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.ActorImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__DESCRIPTION = eINSTANCE.getActor_Description();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.ConceptImpl <em>Concept</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.ConceptImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getConcept()
     * @generated
     */
    EClass CONCEPT = eINSTANCE.getConcept();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCEPT__NAME = eINSTANCE.getConcept_Name();

    /**
     * The meta object literal for the '<em><b>Concept Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCEPT__CONCEPT_DESCRIPTION = eINSTANCE.getConcept_ConceptDescription();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.UseCaseImpl <em>Use Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCaseImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getUseCase()
     * @generated
     */
    EClass USE_CASE = eINSTANCE.getUseCase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NAME = eINSTANCE.getUseCase_Name();

    /**
     * The meta object literal for the '<em><b>Use Case Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__USE_CASE_NAME = eINSTANCE.getUseCase_UseCaseName();

    /**
     * The meta object literal for the '<em><b>Actors</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__ACTORS = eINSTANCE.getUseCase_Actors();

    /**
     * The meta object literal for the '<em><b>Concepts</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__CONCEPTS = eINSTANCE.getUseCase_Concepts();

    /**
     * The meta object literal for the '<em><b>Use Cases Flow</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__USE_CASES_FLOW = eINSTANCE.getUseCase_UseCasesFlow();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.UseCaseFlowImpl <em>Flow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCaseFlowImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getUseCaseFlow()
     * @generated
     */
    EClass USE_CASE_FLOW = eINSTANCE.getUseCaseFlow();

    /**
     * The meta object literal for the '<em><b>Complete Actions Block</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_FLOW__COMPLETE_ACTIONS_BLOCK = eINSTANCE.getUseCaseFlow_CompleteActionsBlock();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.CompleteActionBlockImpl <em>Complete Action Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.CompleteActionBlockImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getCompleteActionBlock()
     * @generated
     */
    EClass COMPLETE_ACTION_BLOCK = eINSTANCE.getCompleteActionBlock();

    /**
     * The meta object literal for the '<em><b>User Actions Block</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLETE_ACTION_BLOCK__USER_ACTIONS_BLOCK = eINSTANCE.getCompleteActionBlock_UserActionsBlock();

    /**
     * The meta object literal for the '<em><b>System Actions Block</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLETE_ACTION_BLOCK__SYSTEM_ACTIONS_BLOCK = eINSTANCE.getCompleteActionBlock_SystemActionsBlock();

    /**
     * The meta object literal for the '{@link mx.kukulkan.dsl.usecase.useCase.impl.SystemActionBlockImpl <em>System Action Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.kukulkan.dsl.usecase.useCase.impl.SystemActionBlockImpl
     * @see mx.kukulkan.dsl.usecase.useCase.impl.UseCasePackageImpl#getSystemActionBlock()
     * @generated
     */
    EClass SYSTEM_ACTION_BLOCK = eINSTANCE.getSystemActionBlock();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_ACTION_BLOCK__NAME = eINSTANCE.getSystemActionBlock_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_ACTION_BLOCK__DESCRIPTION = eINSTANCE.getSystemActionBlock_Description();

  }

} //UseCasePackage
