/*
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.ui.tests;

import com.google.inject.Injector;
import mx.kukulkan.dsl.usecase.ui.internal.UsecaseActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class UseCaseUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UsecaseActivator.getInstance().getInjector("mx.kukulkan.dsl.usecase.UseCase");
	}

}
