/**
 * generated by Xtext 2.16.0
 */
package mx.kukulkan.dsl.usecase.useCase.impl;

import java.util.Collection;

import mx.kukulkan.dsl.usecase.useCase.Actor;
import mx.kukulkan.dsl.usecase.useCase.Concept;
import mx.kukulkan.dsl.usecase.useCase.RequirementsUseCaseModel;
import mx.kukulkan.dsl.usecase.useCase.UseCase;
import mx.kukulkan.dsl.usecase.useCase.UseCasePackage;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Requirements Use Case Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl#getActors <em>Actors</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl#getData <em>Data</em>}</li>
 *   <li>{@link mx.kukulkan.dsl.usecase.useCase.impl.RequirementsUseCaseModelImpl#getUsecases <em>Usecases</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RequirementsUseCaseModelImpl extends MinimalEObjectImpl.Container implements RequirementsUseCaseModel
{
  /**
   * The cached value of the '{@link #getActors() <em>Actors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActors()
   * @generated
   * @ordered
   */
  protected EList<Actor> actors;

  /**
   * The cached value of the '{@link #getData() <em>Data</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData()
   * @generated
   * @ordered
   */
  protected EList<Concept> data;

  /**
   * The cached value of the '{@link #getUsecases() <em>Usecases</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsecases()
   * @generated
   * @ordered
   */
  protected EList<UseCase> usecases;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequirementsUseCaseModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UseCasePackage.Literals.REQUIREMENTS_USE_CASE_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Actor> getActors()
  {
    if (actors == null)
    {
      actors = new EObjectContainmentEList<Actor>(Actor.class, this, UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS);
    }
    return actors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Concept> getData()
  {
    if (data == null)
    {
      data = new EObjectContainmentEList<Concept>(Concept.class, this, UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA);
    }
    return data;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<UseCase> getUsecases()
  {
    if (usecases == null)
    {
      usecases = new EObjectContainmentEList<UseCase>(UseCase.class, this, UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES);
    }
    return usecases;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS:
        return ((InternalEList<?>)getActors()).basicRemove(otherEnd, msgs);
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA:
        return ((InternalEList<?>)getData()).basicRemove(otherEnd, msgs);
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES:
        return ((InternalEList<?>)getUsecases()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS:
        return getActors();
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA:
        return getData();
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES:
        return getUsecases();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS:
        getActors().clear();
        getActors().addAll((Collection<? extends Actor>)newValue);
        return;
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA:
        getData().clear();
        getData().addAll((Collection<? extends Concept>)newValue);
        return;
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES:
        getUsecases().clear();
        getUsecases().addAll((Collection<? extends UseCase>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS:
        getActors().clear();
        return;
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA:
        getData().clear();
        return;
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES:
        getUsecases().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__ACTORS:
        return actors != null && !actors.isEmpty();
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__DATA:
        return data != null && !data.isEmpty();
      case UseCasePackage.REQUIREMENTS_USE_CASE_MODEL__USECASES:
        return usecases != null && !usecases.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RequirementsUseCaseModelImpl
